# Generated by Django 3.2.9 on 2022-10-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='아이디')),
                ('user_name', models.CharField(max_length=200, verbose_name='이름')),
                ('user_pass', models.CharField(max_length=200, verbose_name='비밀번호')),
                ('recent_login', models.DateTimeField(verbose_name='최근 로그인')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name_plural': '유저',
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
