# Generated by Django 3.2.9 on 2022-11-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_user_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('achiv_name', models.CharField(max_length=200, verbose_name='업적명')),
            ],
            options={
                'verbose_name_plural': '주소',
                'db_table': 'achivement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAchivement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visible_chk', models.BooleanField(default=True)),
                ('achiv_id', models.ForeignKey(db_column='achiv_id', on_delete=django.db.models.deletion.CASCADE, related_name='userAchiv_achiv', to='adminpage.achivement')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='userAchiv_user', to='adminpage.user')),
            ],
            options={
                'verbose_name_plural': '주소',
                'db_table': 'user_achivement',
                'managed': True,
            },
        ),
    ]
