# Generated by Django 3.2.9 on 2022-11-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_achivement_userachivement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surv_name', models.CharField(max_length=200, verbose_name='설문조사명')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name_plural': '설문조사',
                'db_table': 'survey',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='achivement',
            options={'managed': True, 'verbose_name_plural': '업적'},
        ),
        migrations.AlterModelOptions(
            name='userachivement',
            options={'managed': True, 'verbose_name_plural': '유저-업적'},
        ),
        migrations.AddField(
            model_name='user',
            name='achives',
            field=models.ManyToManyField(through='adminpage.UserAchivement', to='adminpage.Achivement'),
        ),
        migrations.CreateModel(
            name='SurveyQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surv_q_content', models.CharField(max_length=200, verbose_name='설문조사 질문')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('surv_id', models.ForeignKey(db_column='surv_id', on_delete=django.db.models.deletion.CASCADE, related_name='surv_survQ', to='adminpage.survey')),
            ],
            options={
                'verbose_name_plural': '설문조사 질문',
                'db_table': 'survey_q',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surv_a_content', models.CharField(max_length=200, verbose_name='설문조사 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('surv_q_id', models.ForeignKey(db_column='surv_q_id', on_delete=django.db.models.deletion.CASCADE, related_name='survQ_survA', to='adminpage.surveyq')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_survA', to='adminpage.user')),
            ],
            options={
                'verbose_name_plural': '설문조사 응답',
                'db_table': 'survey_a',
                'managed': True,
            },
        ),
    ]
